(function () {
  const languages = {
    English: { code: "en", native: "English" },
    "தமிழ்": { code: "ta", native: "தமிழ்" },
    "हिन्दी": { code: "hi", native: "हिन्दी" },
    "తెలుగు": { code: "te", native: "తెలుగు" },
    "മലയാളം": { code: "ml", native: "മലയാളം" },
    "ಕನ್ನಡ": { code: "kn", native: "ಕನ್ನಡ" },
    "বাংলা": { code: "bn", native: "বাংলা" },
    "मराठी": { code: "mr", native: "मराठी" },
    "ગુજરાતી": { code: "gu", native: "ગુજરાતી" }
  };

  const en = {
    myFitness:"MY FITNESS", home:"Home", workouts:"Workouts", nutrition:"Nutrition", progress:"Progress",
    coach:"FitSugar Coach", myGym:"MY GYM", membership:"Membership", owner:"Owner Console",
    unlock:"Unlock your best", unlockDesc:"Custom plans, deeper insights, zero limits.", explore:"Explore Pro",
    search:"Search workouts, food, plans...", greeting:"Good morning", greetingSub:"Small steps, strong habits. Let’s make today count.",
    streak:"12 day streak", best:"Your best: 18 days", todayWorkout:"TODAY'S WORKOUT", upper:"Upper Body Strength",
    start:"Start workout", glucose:"GLUCOSE CHECK-IN", inRange:"You're in range", stable:"Stable", logReading:"+ Log new reading",
    weekly:"Your weekly plan", fullPlan:"View full plan →", fuel:"FUEL YOUR DAY", upNext:"Up next",
    fullMeal:"Full meal plan →", askMind:"Anything on your mind?", askDesc:"Ask about form, food, glucose, or make a plan that works around your day.",
    askCoach:"Ask Coach", safety:"Your safety matters.", safetyDesc:"If you have diabetes, heart or blood pressure concerns, are pregnant, or recovering from injury, consult a qualified doctor before changing your workout or diet.",
    workoutLibrary:"Workout library", workoutDesc:"Trainer-built sessions with clear form cues and safety notes.", buildPlan:"+ Build a plan",
    all:"All", chest:"Chest", back:"Back", legs:"Legs", arms:"Arms", shoulders:"Shoulders", fullBody:"Full body",
    rooted:"ROOTED IN YOUR REGION", foodHome:"Food that feels like home", foodDesc:"Practical nutrition for your goals, preferences, and glucose profile.",
    smartPlate:"Your plate, intelligently balanced.", smartDesc:"Higher fibre, 82g protein, familiar ingredients—and no joyless “diet food”.",
    viewToday:"View today's plan", swap:"Swap a meal", todayMenu:"TODAY'S MENU", fiveMeals:"Five steady-energy meals",
    smartSips:"SMART SIPS", proteinTitle:"Protein without the sugar rush", alternatives:"Alternatives", hide:"Hide alternatives",
    choose:"Choose this", selected:"Meal alternative selected", kcal:"kcal", protein:"protein",
    progressTitle:"Your progress", progressDesc:"The numbers that matter—without letting them run the show.", checkin:"+ Weekly check-in",
    membershipTitle:"Membership", membershipDesc:"Your plan, visits, payments, and trainer in one place.",
    business:"Business overview", businessDesc:"Here’s how your gym is moving.", addMember:"+ Add member",
    coachIntro:"Practical answers tuned to your goals, food, region, and health profile.", online:"Online · Knows your plan",
    meal1:"Vegetable idli + sambar", meal1d:"3 mini idlis, extra dal sambar", meal1a:"Ragi dosa + sambar|Oats vegetable upma|Pesarattu + chutney",
    meal2:"Sundal cup", meal2d:"Chickpeas, coconut, cucumber", meal2a:"Sprout chaat|Roasted chana + cucumber|Boiled egg + salad",
    meal3:"Millet rice + dal", meal3d:"Vegetable poriyal and curd", meal3a:"2 rotis + dal + sabzi|Red rice + fish curry|Millet khichdi + curd",
    meal4:"Spiced buttermilk", meal4d:"With roasted peanut chaat", meal4a:"Unsweetened lassi|Green tea + roasted chana|Sprouts smoothie",
    meal5:"Paneer vegetable dosa", meal5d:"Mint chutney, no added sugar", meal5a:"Vegetable omelette + roti|Tofu millet bowl|Grilled fish + vegetables",
    drink1:"Ragi recovery malt", drink1a:"Unsweetened whey in water|Plant protein + cinnamon|Buttermilk + roasted gram",
    drink2:"Peanut banana shake", drink2a:"Peanut cocoa shake|Paneer berry smoothie|Egg + banana meal",
    drink3:"Mint buttermilk", drink3a:"Cucumber chaas|Plain kefir|Lemon ginger water + sprouts"
  };

  const translations = {
    ta:{myFitness:"என் உடற்பயிற்சி",home:"முகப்பு",workouts:"உடற்பயிற்சிகள்",nutrition:"ஊட்டச்சத்து",progress:"முன்னேற்றம்",coach:"FitSugar பயிற்சியாளர்",myGym:"என் ஜிம்",membership:"உறுப்பினர் திட்டம்",owner:"உரிமையாளர் மையம்",unlock:"உங்கள் சிறந்த நிலையை அடையுங்கள்",explore:"Pro-ஐ பார்க்க",search:"உடற்பயிற்சி, உணவு, திட்டங்களைத் தேடுங்கள்...",greeting:"காலை வணக்கம், அருண்",greetingSub:"சிறிய படிகள், வலுவான பழக்கங்கள். இன்றை சிறப்பாக்குவோம்.",streak:"12 நாள் தொடர்ச்சி",todayWorkout:"இன்றைய உடற்பயிற்சி",upper:"மேல் உடல் வலிமை",start:"தொடங்குங்கள்",glucose:"குளுக்கோஸ் பதிவு",inRange:"அளவு சரியாக உள்ளது",stable:"நிலையானது",logReading:"+ புதிய அளவை பதிவு செய்",weekly:"உங்கள் வார திட்டம்",fullPlan:"முழு திட்டம் →",fuel:"இன்றைய ஊட்டம்",upNext:"அடுத்து",fullMeal:"முழு உணவுத் திட்டம் →",askMind:"என்ன கேட்க விரும்புகிறீர்கள்?",askCoach:"பயிற்சியாளரிடம் கேளுங்கள்",safety:"உங்கள் பாதுகாப்பு முக்கியம்.",workoutLibrary:"உடற்பயிற்சி நூலகம்",workoutDesc:"வடிவம் மற்றும் பாதுகாப்பு குறிப்புகளுடன் பயிற்சியாளர் உருவாக்கிய அமர்வுகள்.",buildPlan:"+ திட்டம் உருவாக்கு",all:"அனைத்தும்",chest:"மார்பு",back:"முதுகு",legs:"கால்கள்",arms:"கைகள்",shoulders:"தோள்கள்",fullBody:"முழு உடல்",rooted:"உங்கள் பகுதிக்கேற்ப",foodHome:"வீட்டு சுவையில் ஆரோக்கிய உணவு",foodDesc:"உங்கள் இலக்கு, விருப்பம் மற்றும் குளுக்கோஸுக்கேற்ற நடைமுறை ஊட்டச்சத்து.",smartPlate:"அறிவுடன் சமநிலைப்படுத்திய தட்டு.",viewToday:"இன்றைய திட்டம்",swap:"உணவை மாற்று",todayMenu:"இன்றைய உணவு",fiveMeals:"நிலையான ஆற்றலுக்கான ஐந்து உணவுகள்",smartSips:"ஆரோக்கிய பானங்கள்",proteinTitle:"சர்க்கரை உயர்வில்லா புரதம்",alternatives:"மாற்று உணவுகள்",hide:"மாற்றுகளை மறை",choose:"இதைத் தேர்வு செய்",selected:"மாற்று உணவு தேர்ந்தெடுக்கப்பட்டது",progressTitle:"உங்கள் முன்னேற்றம்",checkin:"+ வாராந்திர பதிவு",membershipTitle:"உறுப்பினர் திட்டம்",business:"வணிக சுருக்கம்",addMember:"+ உறுப்பினர் சேர்",coachIntro:"உங்கள் இலக்கு, உணவு, பகுதி மற்றும் உடல்நிலைக்கேற்ற நடைமுறை பதில்கள்.",meal1:"காய்கறி இட்லி + சாம்பார்",meal1d:"3 சிறிய இட்லி, அதிக பருப்பு சாம்பார்",meal1a:"ராகி தோசை + சாம்பார்|ஓட்ஸ் காய்கறி உப்புமா|பெசரட்டு + சட்னி",meal2:"சுண்டல் கப்",meal2d:"கொண்டைக்கடலை, தேங்காய், வெள்ளரி",meal2a:"முளைகட்டிய பயறு சாட்|வறுத்த கடலை + வெள்ளரி|வேகவைத்த முட்டை + சாலட்",meal3:"சிறுதானிய சாதம் + பருப்பு",meal3d:"காய்கறி பொரியல் மற்றும் தயிர்",meal3a:"2 சப்பாத்தி + பருப்பு + காய்கறி|சிவப்பு அரிசி + மீன் குழம்பு|சிறுதானிய கிச்சடி + தயிர்",meal4:"மசாலா மோர்",meal4d:"வறுத்த வேர்க்கடலை சாட் உடன்",meal4a:"சர்க்கரை இல்லா லஸ்ஸி|பச்சை தேநீர் + வறுத்த கடலை|முளைகட்டிய பயறு ஸ்மூத்தி",meal5:"பனீர் காய்கறி தோசை",meal5d:"புதினா சட்னி, சர்க்கரை இல்லை",meal5a:"காய்கறி ஆம்லெட் + சப்பாத்தி|டோஃபு சிறுதானிய கிண்ணம்|கிரில் மீன் + காய்கறிகள்"},
    hi:{myFitness:"मेरी फिटनेस",home:"होम",workouts:"वर्कआउट",nutrition:"पोषण",progress:"प्रगति",coach:"FitSugar कोच",myGym:"मेरा जिम",membership:"सदस्यता",owner:"ओनर कंसोल",unlock:"अपना सर्वश्रेष्ठ पाएं",explore:"Pro देखें",search:"वर्कआउट, भोजन और प्लान खोजें...",greeting:"सुप्रभात, अरुण",greetingSub:"छोटे कदम, मजबूत आदतें। आज को बेहतर बनाएं।",streak:"12 दिन की स्ट्रीक",todayWorkout:"आज का वर्कआउट",upper:"अपर बॉडी स्ट्रेंथ",start:"वर्कआउट शुरू करें",glucose:"ग्लूकोज़ चेक-इन",inRange:"आप सही सीमा में हैं",stable:"स्थिर",logReading:"+ नई रीडिंग दर्ज करें",weekly:"आपका साप्ताहिक प्लान",fullPlan:"पूरा प्लान देखें →",fuel:"आज का पोषण",upNext:"अगला भोजन",fullMeal:"पूरा भोजन प्लान →",askMind:"क्या पूछना चाहते हैं?",askCoach:"कोच से पूछें",safety:"आपकी सुरक्षा महत्वपूर्ण है।",workoutLibrary:"वर्कआउट लाइब्रेरी",workoutDesc:"फॉर्म और सुरक्षा निर्देशों के साथ ट्रेनर द्वारा बनाए सत्र।",buildPlan:"+ प्लान बनाएं",all:"सभी",chest:"छाती",back:"पीठ",legs:"पैर",arms:"बांहें",shoulders:"कंधे",fullBody:"पूरा शरीर",rooted:"आपके क्षेत्र के अनुसार",foodHome:"घर जैसा स्वस्थ खाना",foodDesc:"आपके लक्ष्य, पसंद और ग्लूकोज़ के अनुसार व्यावहारिक पोषण।",smartPlate:"समझदारी से संतुलित थाली।",viewToday:"आज का प्लान देखें",swap:"भोजन बदलें",todayMenu:"आज का मेन्यू",fiveMeals:"स्थिर ऊर्जा वाले पाँच भोजन",smartSips:"स्मार्ट ड्रिंक्स",proteinTitle:"बिना शुगर स्पाइक का प्रोटीन",alternatives:"विकल्प",hide:"विकल्प छिपाएं",choose:"इसे चुनें",selected:"भोजन विकल्प चुना गया",progressTitle:"आपकी प्रगति",checkin:"+ साप्ताहिक चेक-इन",membershipTitle:"सदस्यता",business:"बिज़नेस सारांश",addMember:"+ सदस्य जोड़ें",coachIntro:"आपके लक्ष्य, भोजन, क्षेत्र और स्वास्थ्य के अनुसार उपयोगी उत्तर।",meal1:"वेजिटेबल इडली + सांभर",meal1d:"3 मिनी इडली, अधिक दाल वाला सांभर",meal1a:"रागी डोसा + सांभर|ओट्स वेज उपमा|पेसरट्टू + चटनी",meal2:"सुंदल कप",meal2d:"चना, नारियल, खीरा",meal2a:"स्प्राउट चाट|भुना चना + खीरा|उबला अंडा + सलाद",meal3:"मिलेट चावल + दाल",meal3d:"सब्ज़ी पोरियल और दही",meal3a:"2 रोटी + दाल + सब्ज़ी|लाल चावल + फिश करी|मिलेट खिचड़ी + दही",meal4:"मसाला छाछ",meal4d:"भुनी मूंगफली चाट के साथ",meal4a:"बिना चीनी लस्सी|ग्रीन टी + भुना चना|स्प्राउट स्मूदी",meal5:"पनीर वेज डोसा",meal5d:"पुदीना चटनी, बिना चीनी",meal5a:"वेज ऑमलेट + रोटी|टोफू मिलेट बाउल|ग्रिल्ड फिश + सब्ज़ियाँ"},
    te:{myFitness:"నా ఫిట్‌నెస్",home:"హోమ్",workouts:"వ్యాయామాలు",nutrition:"పోషణ",progress:"పురోగతి",coach:"FitSugar కోచ్",myGym:"నా జిమ్",membership:"సభ్యత్వం",owner:"ఓనర్ కన్సోల్",search:"వ్యాయామాలు, ఆహారం, ప్లాన్లు వెతకండి...",greeting:"శుభోదయం, అరుణ్",greetingSub:"చిన్న అడుగులు, బలమైన అలవాట్లు. ఈ రోజును సార్థకం చేద్దాం.",streak:"12 రోజుల వరుస",todayWorkout:"నేటి వ్యాయామం",upper:"ఎగువ శరీర బలం",start:"వ్యాయామం ప్రారంభించండి",glucose:"గ్లూకోజ్ చెక్-ఇన్",inRange:"మీరు సరైన పరిధిలో ఉన్నారు",stable:"స్థిరంగా",logReading:"+ కొత్త రీడింగ్ నమోదు",weekly:"మీ వారపు ప్లాన్",fullPlan:"పూర్తి ప్లాన్ →",fuel:"నేటి పోషణ",upNext:"తదుపరి",fullMeal:"పూర్తి భోజన ప్లాన్ →",askMind:"ఏమి అడగాలనుకుంటున్నారు?",askCoach:"కోచ్‌ను అడగండి",safety:"మీ భద్రత ముఖ్యం.",workoutLibrary:"వ్యాయామ లైబ్రరీ",buildPlan:"+ ప్లాన్ తయారు చేయండి",all:"అన్నీ",chest:"ఛాతీ",back:"వీపు",legs:"కాళ్లు",arms:"చేతులు",shoulders:"భుజాలు",fullBody:"పూర్తి శరీరం",foodHome:"ఇంటి రుచితో ఆరోగ్యకరమైన ఆహారం",foodDesc:"మీ లక్ష్యం, అభిరుచి, గ్లూకోజ్‌కు సరిపోయే పోషణ.",smartPlate:"తెలివిగా సమతుల్యమైన ప్లేట్.",viewToday:"నేటి ప్లాన్ చూడండి",swap:"భోజనం మార్చండి",todayMenu:"నేటి మెనూ",fiveMeals:"స్థిర శక్తికి ఐదు భోజనాలు",proteinTitle:"షుగర్ స్పైక్ లేని ప్రోటీన్",alternatives:"ప్రత్యామ్నాయాలు",hide:"ప్రత్యామ్నాయాలను దాచు",choose:"దీన్ని ఎంచుకోండి",selected:"ప్రత్యామ్నాయ భోజనం ఎంపికైంది",progressTitle:"మీ పురోగతి",membershipTitle:"సభ్యత్వం",business:"వ్యాపార సారాంశం",addMember:"+ సభ్యుడిని చేర్చండి",meal1:"కూరగాయల ఇడ్లీ + సాంబార్",meal1d:"3 మినీ ఇడ్లీలు, ఎక్కువ పప్పు సాంబార్",meal1a:"రాగి దోసె + సాంబార్|ఓట్స్ వెజ్ ఉప్మా|పెసరట్టు + చట్నీ",meal2:"సుండల్ కప్",meal2d:"శనగలు, కొబ్బరి, దోసకాయ",meal2a:"మొలకల చాట్|వేయించిన శనగలు + దోసకాయ|ఉడికిన గుడ్డు + సలాడ్",meal3:"మిల్లెట్ అన్నం + పప్పు",meal3d:"కూరగాయల వేపుడు మరియు పెరుగు",meal3a:"2 రొట్టెలు + పప్పు + కూర|ఎర్ర బియ్యం + చేపల కూర|మిల్లెట్ కిచిడీ + పెరుగు",meal4:"మసాలా మజ్జిగ",meal4d:"వేయించిన వేరుశెనగ చాట్‌తో",meal4a:"చక్కెర లేని లస్సీ|గ్రీన్ టీ + శనగలు|మొలకల స్మూతీ",meal5:"పనీర్ వెజ్ దోసె",meal5d:"పుదీనా చట్నీ, చక్కెర లేదు",meal5a:"వెజ్ ఆమ్లెట్ + రొట్టె|టోఫు మిల్లెట్ బౌల్|గ్రిల్డ్ చేప + కూరగాయలు"},
    ml:{myFitness:"എന്റെ ഫിറ്റ്നസ്",home:"ഹോം",workouts:"വ്യായാമങ്ങൾ",nutrition:"പോഷണം",progress:"പുരോഗതി",coach:"FitSugar കോച്ച്",myGym:"എന്റെ ജിം",membership:"അംഗത്വം",owner:"ഉടമ കൺസോൾ",search:"വ്യായാമം, ഭക്ഷണം, പ്ലാനുകൾ തിരയുക...",greeting:"സുപ്രഭാതം, അരുൺ",greetingSub:"ചെറിയ ചുവടുകൾ, ശക്തമായ ശീലങ്ങൾ. ഇന്ന് മികച്ചതാക്കാം.",streak:"12 ദിവസത്തെ തുടർച്ച",todayWorkout:"ഇന്നത്തെ വ്യായാമം",upper:"അപ്പർ ബോഡി സ്ട്രെങ്ത്",start:"വ്യായാമം തുടങ്ങുക",glucose:"ഗ്ലൂക്കോസ് ചെക്ക്-ഇൻ",inRange:"നിങ്ങൾ ശരിയായ പരിധിയിലാണ്",stable:"സ്ഥിരം",logReading:"+ പുതിയ റീഡിംഗ് ചേർക്കുക",weekly:"നിങ്ങളുടെ ആഴ്ച പ്ലാൻ",fullPlan:"മുഴുവൻ പ്ലാൻ →",fuel:"ഇന്നത്തെ പോഷണം",upNext:"അടുത്തത്",fullMeal:"മുഴുവൻ ഭക്ഷണ പ്ലാൻ →",askMind:"എന്താണ് ചോദിക്കാനുള്ളത്?",askCoach:"കോച്ചിനോട് ചോദിക്കുക",safety:"നിങ്ങളുടെ സുരക്ഷ പ്രധാനമാണ്.",workoutLibrary:"വ്യായാമ ലൈബ്രറി",buildPlan:"+ പ്ലാൻ തയ്യാറാക്കുക",all:"എല്ലാം",chest:"നെഞ്ച്",back:"പുറം",legs:"കാലുകൾ",arms:"കൈകൾ",shoulders:"തോളുകൾ",fullBody:"മുഴുവൻ ശരീരം",foodHome:"വീട്ടുരുചിയുള്ള ആരോഗ്യഭക്ഷണം",foodDesc:"നിങ്ങളുടെ ലക്ഷ്യം, ഇഷ്ടം, ഗ്ലൂക്കോസ് എന്നിവയ്ക്കനുസരിച്ച പോഷണം.",smartPlate:"ബുദ്ധിപൂർവ്വം സന്തുലിതമായ പ്ലേറ്റ്.",viewToday:"ഇന്നത്തെ പ്ലാൻ",swap:"ഭക്ഷണം മാറ്റുക",todayMenu:"ഇന്നത്തെ മെനു",fiveMeals:"സ്ഥിരമായ ഊർജത്തിനായി അഞ്ച് ഭക്ഷണങ്ങൾ",proteinTitle:"ഷുഗർ സ്പൈക്ക് ഇല്ലാത്ത പ്രോട്ടീൻ",alternatives:"പകരം ഭക്ഷണങ്ങൾ",hide:"പകരങ്ങൾ മറയ്ക്കുക",choose:"ഇത് തിരഞ്ഞെടുക്കുക",selected:"പകരം ഭക്ഷണം തിരഞ്ഞെടുത്തു",progressTitle:"നിങ്ങളുടെ പുരോഗതി",membershipTitle:"അംഗത്വം",business:"ബിസിനസ് അവലോകനം",addMember:"+ അംഗത്തെ ചേർക്കുക",meal1:"വെജിറ്റബിൾ ഇഡ്ഡലി + സാമ്പാർ",meal1d:"3 മിനി ഇഡ്ഡലി, കൂടുതൽ പരിപ്പ് സാമ്പാർ",meal1a:"റാഗി ദോശ + സാമ്പാർ|ഓട്സ് വെജ് ഉപ്മാവ്|പെസരട്ട് + ചട്നി",meal2:"സുണ്ടൽ കപ്പ്",meal2d:"കടല, തേങ്ങ, വെള്ളരിക്ക",meal2a:"മുളപ്പിച്ച പയർ ചാട്ട്|വറുത്ത കടല + വെള്ളരിക്ക|പുഴുങ്ങിയ മുട്ട + സാലഡ്",meal3:"മില്ലറ്റ് ചോറ് + പരിപ്പ്",meal3d:"പച്ചക്കറി തോരനും തൈരും",meal3a:"2 റൊട്ടി + പരിപ്പ് + പച്ചക്കറി|ചുവന്ന അരി + മീൻകറി|മില്ലറ്റ് കിച്ചഡി + തൈര്",meal4:"മസാല മോര്",meal4d:"വറുത്ത നിലക്കടല ചാട്ടിനൊപ്പം",meal4a:"പഞ്ചസാരയില്ലാത്ത ലസ്സി|ഗ്രീൻ ടീ + വറുത്ത കടല|മുളപ്പിച്ച പയർ സ്മൂത്തി",meal5:"പനീർ വെജ് ദോശ",meal5d:"പുതിന ചട്നി, പഞ്ചസാര ഇല്ല",meal5a:"വെജ് ഓംലെറ്റ് + റൊട്ടി|ടോഫു മില്ലറ്റ് ബൗൾ|ഗ്രിൽഡ് മീൻ + പച്ചക്കറി"},
    kn:{myFitness:"ನನ್ನ ಫಿಟ್ನೆಸ್",home:"ಮುಖಪುಟ",workouts:"ವ್ಯಾಯಾಮಗಳು",nutrition:"ಪೋಷಣೆ",progress:"ಪ್ರಗತಿ",coach:"FitSugar ಕೋಚ್",myGym:"ನನ್ನ ಜಿಮ್",membership:"ಸದಸ್ಯತ್ವ",owner:"ಮಾಲೀಕರ ಕನ್ಸೋಲ್",search:"ವ್ಯಾಯಾಮ, ಆಹಾರ, ಯೋಜನೆ ಹುಡುಕಿ...",greeting:"ಶುಭೋದಯ, ಅರುಣ್",greetingSub:"ಸಣ್ಣ ಹೆಜ್ಜೆಗಳು, ಬಲವಾದ ಅಭ್ಯಾಸಗಳು. ಇಂದು ಉತ್ತಮವಾಗಿಸೋಣ.",streak:"12 ದಿನಗಳ ಸರಣಿ",todayWorkout:"ಇಂದಿನ ವ್ಯಾಯಾಮ",upper:"ಮೇಲ್ಭಾಗದ ಶಕ್ತಿ",start:"ವ್ಯಾಯಾಮ ಆರಂಭಿಸಿ",glucose:"ಗ್ಲೂಕೋಸ್ ಚೆಕ್-ಇನ್",inRange:"ನೀವು ಸರಿಯಾದ ಮಿತಿಯಲ್ಲಿದ್ದೀರಿ",stable:"ಸ್ಥಿರ",logReading:"+ ಹೊಸ ರೀಡಿಂಗ್ ಸೇರಿಸಿ",weekly:"ನಿಮ್ಮ ವಾರದ ಯೋಜನೆ",fullPlan:"ಪೂರ್ಣ ಯೋಜನೆ →",fuel:"ಇಂದಿನ ಪೋಷಣೆ",upNext:"ಮುಂದಿನದು",fullMeal:"ಪೂರ್ಣ ಆಹಾರ ಯೋಜನೆ →",askMind:"ಏನು ಕೇಳಲು ಬಯಸುತ್ತೀರಿ?",askCoach:"ಕೋಚ್‌ಗೆ ಕೇಳಿ",safety:"ನಿಮ್ಮ ಸುರಕ್ಷತೆ ಮುಖ್ಯ.",workoutLibrary:"ವ್ಯಾಯಾಮ ಗ್ರಂಥಾಲಯ",buildPlan:"+ ಯೋಜನೆ ರಚಿಸಿ",all:"ಎಲ್ಲಾ",chest:"ಎದೆ",back:"ಬೆನ್ನು",legs:"ಕಾಲುಗಳು",arms:"ತೋಳುಗಳು",shoulders:"ಭುಜಗಳು",fullBody:"ಪೂರ್ಣ ದೇಹ",foodHome:"ಮನೆಯ ರುಚಿಯ ಆರೋಗ್ಯಕರ ಆಹಾರ",foodDesc:"ನಿಮ್ಮ ಗುರಿ, ಆಯ್ಕೆ ಮತ್ತು ಗ್ಲೂಕೋಸ್‌ಗೆ ಹೊಂದುವ ಪೋಷಣೆ.",smartPlate:"ಜಾಣ್ಮೆಯಿಂದ ಸಮತೋಲನಗೊಂಡ ತಟ್ಟೆ.",viewToday:"ಇಂದಿನ ಯೋಜನೆ",swap:"ಆಹಾರ ಬದಲಿಸಿ",todayMenu:"ಇಂದಿನ ಮೆನು",fiveMeals:"ಸ್ಥಿರ ಶಕ್ತಿಗಾಗಿ ಐದು ಊಟಗಳು",proteinTitle:"ಶುಗರ್ ಸ್ಪೈಕ್ ಇಲ್ಲದ ಪ್ರೋಟೀನ್",alternatives:"ಪರ್ಯಾಯಗಳು",hide:"ಪರ್ಯಾಯಗಳನ್ನು ಮರೆಮಾಡಿ",choose:"ಇದನ್ನು ಆಯ್ಕೆಮಾಡಿ",selected:"ಪರ್ಯಾಯ ಆಹಾರ ಆಯ್ಕೆಯಾಗಿದೆ",progressTitle:"ನಿಮ್ಮ ಪ್ರಗತಿ",membershipTitle:"ಸದಸ್ಯತ್ವ",business:"ವ್ಯವಹಾರ ಅವಲೋಕನ",addMember:"+ ಸದಸ್ಯರನ್ನು ಸೇರಿಸಿ",meal1:"ತರಕಾರಿ ಇಡ್ಲಿ + ಸಾಂಬಾರ್",meal1d:"3 ಮಿನಿ ಇಡ್ಲಿ, ಹೆಚ್ಚು ಬೇಳೆ ಸಾಂಬಾರ್",meal1a:"ರಾಗಿ ದೋಸೆ + ಸಾಂಬಾರ್|ಓಟ್ಸ್ ತರಕಾರಿ ಉಪ್ಪಿಟ್ಟು|ಪೆಸರಟ್ಟು + ಚಟ್ನಿ",meal2:"ಸುಂಡಲ್ ಕಪ್",meal2d:"ಕಡಲೆ, ತೆಂಗಿನಕಾಯಿ, ಸೌತೆಕಾಯಿ",meal2a:"ಮೊಳಕೆ ಕಾಳು ಚಾಟ್|ಹುರಿದ ಕಡಲೆ + ಸೌತೆಕಾಯಿ|ಬೇಯಿಸಿದ ಮೊಟ್ಟೆ + ಸಲಾಡ್",meal3:"ಸಿರಿಧಾನ್ಯ ಅನ್ನ + ಬೇಳೆ",meal3d:"ತರಕಾರಿ ಪಲ್ಯ ಮತ್ತು ಮೊಸರು",meal3a:"2 ರೊಟ್ಟಿ + ಬೇಳೆ + ಪಲ್ಯ|ಕೆಂಪು ಅಕ್ಕಿ + ಮೀನು ಸಾರು|ಸಿರಿಧಾನ್ಯ ಕಿಚಡಿ + ಮೊಸರು",meal4:"ಮಸಾಲೆ ಮಜ್ಜಿಗೆ",meal4d:"ಹುರಿದ ಕಡಲೆಕಾಯಿ ಚಾಟ್ ಜೊತೆ",meal4a:"ಸಕ್ಕರೆರಹಿತ ಲಸ್ಸಿ|ಗ್ರೀನ್ ಟೀ + ಕಡಲೆ|ಮೊಳಕೆ ಸ್ಮೂದಿ",meal5:"ಪನೀರ್ ತರಕಾರಿ ದೋಸೆ",meal5d:"ಪುದೀನಾ ಚಟ್ನಿ, ಸಕ್ಕರೆ ಇಲ್ಲ",meal5a:"ತರಕಾರಿ ಆಮ್ಲೆಟ್ + ರೊಟ್ಟಿ|ಟೋಫು ಸಿರಿಧಾನ್ಯ ಬೌಲ್|ಗ್ರಿಲ್ಡ್ ಮೀನು + ತರಕಾರಿ"},
    bn:{myFitness:"আমার ফিটনেস",home:"হোম",workouts:"ব্যায়াম",nutrition:"পুষ্টি",progress:"অগ্রগতি",coach:"FitSugar কোচ",myGym:"আমার জিম",membership:"সদস্যপদ",owner:"মালিক কনসোল",search:"ব্যায়াম, খাবার ও পরিকল্পনা খুঁজুন...",greeting:"সুপ্রভাত, অরুণ",greetingSub:"ছোট পদক্ষেপ, শক্ত অভ্যাস। আজকে সার্থক করি।",streak:"১২ দিনের ধারাবাহিকতা",todayWorkout:"আজকের ব্যায়াম",upper:"উপরের শরীরের শক্তি",start:"ব্যায়াম শুরু করুন",glucose:"গ্লুকোজ চেক-ইন",inRange:"আপনি সঠিক সীমায় আছেন",stable:"স্থিতিশীল",logReading:"+ নতুন রিডিং যোগ করুন",weekly:"আপনার সাপ্তাহিক পরিকল্পনা",fullPlan:"সম্পূর্ণ পরিকল্পনা →",fuel:"আজকের পুষ্টি",upNext:"পরবর্তী",fullMeal:"সম্পূর্ণ খাবার পরিকল্পনা →",askMind:"কী জানতে চান?",askCoach:"কোচকে জিজ্ঞাসা করুন",safety:"আপনার নিরাপত্তা গুরুত্বপূর্ণ।",workoutLibrary:"ব্যায়াম লাইব্রেরি",buildPlan:"+ পরিকল্পনা তৈরি করুন",all:"সব",chest:"বুক",back:"পিঠ",legs:"পা",arms:"বাহু",shoulders:"কাঁধ",fullBody:"পুরো শরীর",foodHome:"ঘরের স্বাদের স্বাস্থ্যকর খাবার",foodDesc:"আপনার লক্ষ্য, পছন্দ ও গ্লুকোজ অনুযায়ী পুষ্টি।",smartPlate:"বুদ্ধিমত্তায় ভারসাম্যপূর্ণ প্লেট।",viewToday:"আজকের পরিকল্পনা",swap:"খাবার বদলান",todayMenu:"আজকের মেনু",fiveMeals:"স্থির শক্তির পাঁচটি খাবার",proteinTitle:"চিনি বৃদ্ধি ছাড়া প্রোটিন",alternatives:"বিকল্প",hide:"বিকল্প লুকান",choose:"এটি বেছে নিন",selected:"বিকল্প খাবার নির্বাচিত",progressTitle:"আপনার অগ্রগতি",membershipTitle:"সদস্যপদ",business:"ব্যবসার সারাংশ",addMember:"+ সদস্য যোগ করুন",meal1:"সবজি ইডলি + সাম্বার",meal1d:"৩টি মিনি ইডলি, বেশি ডালের সাম্বার",meal1a:"রাগি দোসা + সাম্বার|ওটস সবজি উপমা|পেসারাট্টু + চাটনি",meal2:"সুন্দল কাপ",meal2d:"ছোলা, নারকেল, শসা",meal2a:"স্প্রাউট চাট|ভাজা ছোলা + শসা|সেদ্ধ ডিম + সালাদ",meal3:"মিলেট ভাত + ডাল",meal3d:"সবজি পোরিয়াল ও দই",meal3a:"২ রুটি + ডাল + সবজি|লাল চাল + মাছের ঝোল|মিলেট খিচুড়ি + দই",meal4:"মশলা ছাছ",meal4d:"ভাজা চিনাবাদাম চাটের সাথে",meal4a:"চিনি ছাড়া লস্যি|গ্রিন টি + ভাজা ছোলা|স্প্রাউট স্মুদি",meal5:"পনির সবজি দোসা",meal5d:"পুদিনা চাটনি, চিনি নেই",meal5a:"সবজি অমলেট + রুটি|টোফু মিলেট বোল|গ্রিল মাছ + সবজি"},
    mr:{myFitness:"माझा फिटनेस",home:"मुख्यपृष्ठ",workouts:"व्यायाम",nutrition:"पोषण",progress:"प्रगती",coach:"FitSugar कोच",myGym:"माझी जिम",membership:"सदस्यत्व",owner:"मालक कन्सोल",search:"व्यायाम, अन्न आणि योजना शोधा...",greeting:"शुभ सकाळ, अरुण",greetingSub:"छोटी पावले, मजबूत सवयी. आजचा दिवस उत्तम करूया.",streak:"12 दिवसांची मालिका",todayWorkout:"आजचा व्यायाम",upper:"वरच्या शरीराची ताकद",start:"व्यायाम सुरू करा",glucose:"ग्लुकोज चेक-इन",inRange:"तुम्ही योग्य मर्यादेत आहात",stable:"स्थिर",logReading:"+ नवीन नोंद जोडा",weekly:"तुमची आठवड्याची योजना",fullPlan:"पूर्ण योजना →",fuel:"आजचे पोषण",upNext:"पुढील",fullMeal:"पूर्ण आहार योजना →",askMind:"काय विचारायचे आहे?",askCoach:"कोचला विचारा",safety:"तुमची सुरक्षितता महत्त्वाची आहे.",workoutLibrary:"व्यायाम संग्रह",buildPlan:"+ योजना तयार करा",all:"सर्व",chest:"छाती",back:"पाठ",legs:"पाय",arms:"हात",shoulders:"खांदे",fullBody:"पूर्ण शरीर",foodHome:"घरच्या चवीचे आरोग्यदायी अन्न",foodDesc:"तुमचे ध्येय, आवड आणि ग्लुकोजनुसार पोषण.",smartPlate:"हुशारीने संतुलित ताट.",viewToday:"आजची योजना",swap:"जेवण बदला",todayMenu:"आजचा मेनू",fiveMeals:"स्थिर ऊर्जेसाठी पाच जेवणे",proteinTitle:"साखर न वाढवणारे प्रोटीन",alternatives:"पर्याय",hide:"पर्याय लपवा",choose:"हे निवडा",selected:"पर्यायी जेवण निवडले",progressTitle:"तुमची प्रगती",membershipTitle:"सदस्यत्व",business:"व्यवसाय आढावा",addMember:"+ सदस्य जोडा",meal1:"भाजी इडली + सांबार",meal1d:"3 मिनी इडली, जास्त डाळीचे सांबार",meal1a:"नाचणी डोसा + सांबार|ओट्स भाजी उपमा|पेसरट्टू + चटणी",meal2:"सुंदल कप",meal2d:"हरभरा, नारळ, काकडी",meal2a:"मोड आलेल्या कडधान्यांची चाट|भाजलेला हरभरा + काकडी|उकडलेले अंडे + सॅलड",meal3:"भरड धान्य भात + डाळ",meal3d:"भाजी आणि दही",meal3a:"2 पोळी + डाळ + भाजी|लाल तांदूळ + मासे करी|मिलेट खिचडी + दही",meal4:"मसाला ताक",meal4d:"भाजलेल्या शेंगदाण्यांच्या चाटसोबत",meal4a:"साखर नसलेली लस्सी|ग्रीन टी + हरभरा|स्प्राउट स्मूदी",meal5:"पनीर भाजी डोसा",meal5d:"पुदिना चटणी, साखर नाही",meal5a:"भाजी ऑम्लेट + पोळी|टोफू मिलेट बाउल|ग्रिल्ड मासे + भाज्या"},
    gu:{myFitness:"મારી ફિટનેસ",home:"હોમ",workouts:"કસરતો",nutrition:"પોષણ",progress:"પ્રગતિ",coach:"FitSugar કોચ",myGym:"મારું જિમ",membership:"સભ્યપદ",owner:"માલિક કન્સોલ",search:"કસરત, ખોરાક અને યોજના શોધો...",greeting:"સુપ્રભાત, અરુણ",greetingSub:"નાનાં પગલાં, મજબૂત આદતો. આજનો દિવસ સારો બનાવીએ.",streak:"12 દિવસની સળંગતા",todayWorkout:"આજની કસરત",upper:"ઉપલા શરીરની તાકાત",start:"કસરત શરૂ કરો",glucose:"ગ્લુકોઝ ચેક-ઇન",inRange:"તમે યોગ્ય મર્યાદામાં છો",stable:"સ્થિર",logReading:"+ નવી નોંધ ઉમેરો",weekly:"તમારી સાપ્તાહિક યોજના",fullPlan:"સંપૂર્ણ યોજના →",fuel:"આજનું પોષણ",upNext:"આગળ",fullMeal:"સંપૂર્ણ ભોજન યોજના →",askMind:"શું પૂછવું છે?",askCoach:"કોચને પૂછો",safety:"તમારી સલામતી મહત્વની છે.",workoutLibrary:"કસરત લાઇબ્રેરી",buildPlan:"+ યોજના બનાવો",all:"બધા",chest:"છાતી",back:"પીઠ",legs:"પગ",arms:"હાથ",shoulders:"ખભા",fullBody:"આખું શરીર",foodHome:"ઘરના સ્વાદનું સ્વસ્થ ભોજન",foodDesc:"તમારા લક્ષ્ય, પસંદગી અને ગ્લુકોઝને અનુરૂપ પોષણ.",smartPlate:"સમજદારીથી સંતુલિત થાળી.",viewToday:"આજની યોજના",swap:"ભોજન બદલો",todayMenu:"આજનું મેનુ",fiveMeals:"સ્થિર ઊર્જા માટે પાંચ ભોજન",proteinTitle:"શુગર વધારા વગરનું પ્રોટીન",alternatives:"વિકલ્પો",hide:"વિકલ્પો છુપાવો",choose:"આ પસંદ કરો",selected:"વૈકલ્પિક ભોજન પસંદ થયું",progressTitle:"તમારી પ્રગતિ",membershipTitle:"સભ્યપદ",business:"વ્યવસાય સારાંશ",addMember:"+ સભ્ય ઉમેરો",meal1:"શાકભાજી ઇડલી + સાંભાર",meal1d:"3 મિની ઇડલી, વધુ દાળવાળું સાંભાર",meal1a:"રાગી ઢોસા + સાંભાર|ઓટ્સ શાક ઉપમા|પેસરટ્ટુ + ચટણી",meal2:"સુંડલ કપ",meal2d:"ચણા, નાળિયેર, કાકડી",meal2a:"સ્પ્રાઉટ ચાટ|શેકેલા ચણા + કાકડી|બાફેલું ઈંડું + સલાડ",meal3:"મિલેટ ભાત + દાળ",meal3d:"શાકભાજી અને દહીં",meal3a:"2 રોટલી + દાળ + શાક|લાલ ચોખા + માછલી કરી|મિલેટ ખીચડી + દહીં",meal4:"મસાલા છાશ",meal4d:"શેકેલી મગફળી ચાટ સાથે",meal4a:"ખાંડ વગરની લસ્સી|ગ્રીન ટી + શેકેલા ચણા|સ્પ્રાઉટ સ્મૂધી",meal5:"પનીર શાક ઢોસા",meal5d:"ફુદીના ચટણી, ખાંડ નહીં",meal5a:"શાક ઓમલેટ + રોટલી|ટોફૂ મિલેટ બાઉલ|ગ્રિલ્ડ માછલી + શાક"}
  };

  let code = localStorage.getItem("fitsugar-language") || "en";
  document.documentElement.lang = code;
  function t(key) { return (translations[code] && translations[code][key]) || en[key] || key; }
  function setLanguage(next) {
    code = next;
    localStorage.setItem("fitsugar-language", code);
    document.documentElement.lang = code;
    document.documentElement.dir = "ltr";
    window.dispatchEvent(new CustomEvent("fitsugar:language", { detail: { code } }));
  }
  function languageName() {
    return Object.values(languages).find(item => item.code === code)?.native || "English";
  }
  window.FitSugarI18n = { languages, t, setLanguage, get code(){return code}, languageName };
})();
